# Generated by Django 5.1.3 on 2024-11-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='terms',
            field=models.TextField(),
        ),
    ]
