# Generated by Django 5.1.3 on 2024-11-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_alter_terms_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalagreement',
            name='terms',
            field=models.TextField(),
        ),
    ]
