# Generated by Django 5.1.3 on 2024-11-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0007_loan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
