# Generated by Django 5.1.3 on 2024-12-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0010_loanpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='loan_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='monthly_rent_paid',
            field=models.BooleanField(default=False),
        ),
    ]
